// Generated by pnpm seo:registry:generate. Do not edit manually.
import { assertSeoRegistry, type SeoRegistryRow } from "../../core/seo/registry.ts";
import { fixtureDistrictRouteRegistryFor } from "../../fixture/route-registries.ts";
import { siteProfileFixtures } from "../site-profile.ts";
import { createProjectUrlGrammar } from "../url-grammar.ts";
import type { ProjectSeoTemplateKey } from "./templates.ts";

const grammar = createProjectUrlGrammar(siteProfileFixtures.multiGeo, fixtureDistrictRouteRegistryFor(siteProfileFixtures.multiGeo));

export const projectSeoRegistrySeed = [
  {
    "pageKey": {
      "kind": "home"
    },
    "url": "/",
    "canonical": "/",
    "entityRef": null,
    "targetPhrases": [
      "fixture home intent"
    ],
    "metric": "searchDemand",
    "value": null,
    "source": "fallback_no_data",
    "snapshotDate": "2026-09-24",
    "synthetic": true,
    "tier": "TEST",
    "minimumObjects": 10,
    "defaultRobots": "noindex,follow",
    "templateKey": "home",
    "title": "Недвижимость Приморска — AMS Realty",
    "h1": "Недвижимость Приморска",
    "description": "Подбор недвижимости в Приморске",
    "status": "draft",
    "morphologyApproved": true,
    "release": "starter-v2.1.0",
    "contentGateRule": "listing"
  },
  {
    "pageKey": {
      "kind": "geoHub",
      "geo": "primorsk"
    },
    "url": "/primorsk/",
    "canonical": "/primorsk/",
    "entityRef": "geo:primorsk",
    "targetPhrases": [
      "fixture geo hub intent"
    ],
    "metric": "searchDemand",
    "value": null,
    "source": "fallback_no_data",
    "snapshotDate": "2026-09-24",
    "synthetic": true,
    "tier": "TEST",
    "minimumObjects": 10,
    "defaultRobots": "noindex,follow",
    "templateKey": "geoHub",
    "title": "Недвижимость Приморска — AMS Realty",
    "h1": "Недвижимость Приморска",
    "description": "Квартиры, дома и новостройки в Приморске — 28 объектов.",
    "status": "draft",
    "morphologyApproved": true,
    "release": "starter-v2.1.0",
    "contentGateRule": "listing"
  },
  {
    "pageKey": {
      "kind": "categoryRoot",
      "category": "kvartiry"
    },
    "url": "/kvartiry/",
    "canonical": "/kvartiry/",
    "entityRef": "category:kvartiry",
    "targetPhrases": [
      "fixture root catalog intent"
    ],
    "metric": "searchDemand",
    "value": null,
    "source": "fallback_no_data",
    "snapshotDate": "2026-09-24",
    "synthetic": true,
    "tier": "TEST",
    "minimumObjects": 10,
    "defaultRobots": "noindex,follow",
    "templateKey": "categoryRoot",
    "title": "Квартиры — AMS Realty",
    "h1": "Квартиры",
    "description": "Квартиры — актуальные предложения. 21 объект.",
    "status": "draft",
    "morphologyApproved": true,
    "release": "starter-v2.1.0",
    "contentGateRule": "listing"
  },
  {
    "pageKey": {
      "kind": "categoryGeo",
      "geo": "primorsk",
      "category": "kvartiry"
    },
    "url": "/primorsk/kvartiry/",
    "canonical": "/primorsk/kvartiry/",
    "entityRef": "geo:primorsk/category:kvartiry",
    "targetPhrases": [
      "fixture geo catalog intent"
    ],
    "metric": "searchDemand",
    "value": null,
    "source": "fallback_no_data",
    "snapshotDate": "2026-09-24",
    "synthetic": true,
    "tier": "TEST",
    "minimumObjects": 10,
    "defaultRobots": "noindex,follow",
    "templateKey": "categoryGeo",
    "title": "Квартиры в Приморске — AMS Realty",
    "h1": "Квартиры в Приморске",
    "description": "Квартиры в Приморске — актуальные предложения. 18 объектов.",
    "status": "draft",
    "morphologyApproved": true,
    "release": "starter-v2.1.0",
    "contentGateRule": "listing"
  },
  {
    "pageKey": {
      "kind": "categoryGeoDistrict",
      "geo": "primorsk",
      "category": "kvartiry",
      "district": "severnyy"
    },
    "url": "/primorsk/kvartiry/severnyy/",
    "canonical": "/primorsk/kvartiry/severnyy/",
    "entityRef": "district:severnyy",
    "targetPhrases": [
      "fixture district catalog intent"
    ],
    "metric": "searchDemand",
    "value": null,
    "source": "fallback_no_data",
    "snapshotDate": "2026-09-24",
    "synthetic": true,
    "tier": "TEST",
    "minimumObjects": 10,
    "defaultRobots": "noindex,follow",
    "templateKey": "categoryGeoDistrict",
    "title": "Квартиры на Северном районе в Приморске — AMS Realty",
    "h1": "Квартиры на Северном районе в Приморске",
    "description": "Квартиры на Северном районе в Приморске — актуальные предложения. 12 объектов.",
    "status": "draft",
    "morphologyApproved": true,
    "release": "starter-v2.1.0",
    "contentGateRule": "listing"
  },
  {
    "pageKey": {
      "kind": "categoryGeoFacet",
      "geo": "primorsk",
      "category": "kvartiry",
      "facet": "dvukhkomnatnye"
    },
    "url": "/primorsk/kvartiry/dvukhkomnatnye/",
    "canonical": "/primorsk/kvartiry/dvukhkomnatnye/",
    "entityRef": "facet:dvukhkomnatnye",
    "targetPhrases": [
      "fixture facet catalog intent"
    ],
    "metric": "searchDemand",
    "value": null,
    "source": "fallback_no_data",
    "snapshotDate": "2026-09-24",
    "synthetic": true,
    "tier": "TEST",
    "minimumObjects": 10,
    "defaultRobots": "noindex,follow",
    "templateKey": "categoryGeoFacet",
    "title": "Двухкомнатные квартиры в Приморске — AMS Realty",
    "h1": "Двухкомнатные квартиры в Приморске",
    "description": "Двухкомнатные квартиры в Приморске — актуальные предложения. 11 объектов.",
    "status": "draft",
    "morphologyApproved": true,
    "release": "starter-v2.1.0",
    "contentGateRule": "listing"
  },
  {
    "pageKey": {
      "kind": "geoDevelopers",
      "geo": "primorsk"
    },
    "url": "/primorsk/zastroyshchiki/",
    "canonical": "/primorsk/zastroyshchiki/",
    "entityRef": "geo:primorsk/developers",
    "targetPhrases": [
      "fixture geo developers intent"
    ],
    "metric": "searchDemand",
    "value": null,
    "source": "fallback_no_data",
    "snapshotDate": "2026-09-24",
    "synthetic": true,
    "tier": "TEST",
    "minimumObjects": 10,
    "defaultRobots": "noindex,follow",
    "templateKey": "geoDevelopers",
    "title": "Застройщики в Приморске — AMS Realty",
    "h1": "Застройщики в Приморске",
    "description": "Застройщики и проверенные жилые комплексы в Приморске — 7 объектов.",
    "status": "draft",
    "morphologyApproved": true,
    "release": "starter-v2.1.0",
    "contentGateRule": "developerGeo"
  },
  {
    "pageKey": {
      "kind": "development",
      "developmentKind": "residential_complex",
      "slug": "severnyy-bereg"
    },
    "url": "/novostroyki/zhk-severnyy-bereg/",
    "canonical": "/novostroyki/zhk-severnyy-bereg/",
    "entityRef": "development:severnyy-bereg",
    "targetPhrases": [
      "fixture development normal intent"
    ],
    "metric": "searchDemand",
    "value": null,
    "source": "fallback_no_data",
    "snapshotDate": "2026-09-24",
    "synthetic": true,
    "tier": "TEST",
    "minimumObjects": 10,
    "defaultRobots": "noindex,follow",
    "templateKey": "developmentNormal",
    "title": "ЖК «Северный берег» — AMS Realty",
    "h1": "ЖК «Северный берег»",
    "description": "ЖК «Северный берег» в Приморске — от 6,2 млн ₽.",
    "status": "draft",
    "morphologyApproved": true,
    "release": "starter-v2.1.0",
    "contentGateRule": "development"
  },
  {
    "pageKey": {
      "kind": "development",
      "developmentKind": "cottage_village",
      "slug": "severnyy-bereg"
    },
    "url": "/kottedzhnye-poselki/kp-severnyy-bereg/",
    "canonical": "/kottedzhnye-poselki/kp-severnyy-bereg/",
    "entityRef": "development:severnyy-bereg-kp",
    "targetPhrases": [
      "fixture development collision intent"
    ],
    "metric": "searchDemand",
    "value": null,
    "source": "fallback_no_data",
    "snapshotDate": "2026-09-24",
    "synthetic": true,
    "tier": "TEST",
    "minimumObjects": 10,
    "defaultRobots": "noindex,follow",
    "templateKey": "developmentCollision",
    "title": "КП «Северный берег» в Приморске — AMS Realty",
    "h1": "КП «Северный берег» в Приморске",
    "description": "КП «Северный берег» в Приморске",
    "status": "draft",
    "morphologyApproved": true,
    "release": "starter-v2.1.0",
    "contentGateRule": "development"
  },
  {
    "pageKey": {
      "kind": "developer",
      "slug": "stroy-invest"
    },
    "url": "/zastroyshchiki/stroy-invest/",
    "canonical": "/zastroyshchiki/stroy-invest/",
    "entityRef": "developer:stroy-invest",
    "targetPhrases": [
      "fixture developer intent"
    ],
    "metric": "searchDemand",
    "value": null,
    "source": "fallback_no_data",
    "snapshotDate": "2026-09-24",
    "synthetic": true,
    "tier": "TEST",
    "minimumObjects": 10,
    "defaultRobots": "noindex,follow",
    "templateKey": "developer",
    "title": "Строй Инвест — AMS Realty",
    "h1": "Строй Инвест",
    "description": "Объекты застройщика Строй Инвест в Приморске — 4 объекта.",
    "status": "draft",
    "morphologyApproved": true,
    "release": "starter-v2.1.0",
    "contentGateRule": "developer"
  },
  {
    "pageKey": {
      "kind": "property",
      "category": "kvartiry",
      "semantic": "ulitsa-mira-10",
      "publicUrlId": 42
    },
    "url": "/kvartiry/ulitsa-mira-10-42/",
    "canonical": "/kvartiry/ulitsa-mira-10-42/",
    "entityRef": "property:42",
    "targetPhrases": [
      "fixture property intent"
    ],
    "metric": "searchDemand",
    "value": null,
    "source": "fallback_no_data",
    "snapshotDate": "2026-09-24",
    "synthetic": true,
    "tier": "TEST",
    "minimumObjects": 10,
    "defaultRobots": "noindex,follow",
    "templateKey": "property",
    "title": "2-комнатная квартира, улица Мира, 10 — AMS Realty",
    "h1": "2-комнатная квартира, улица Мира, 10",
    "description": "2-комнатная квартира, улица Мира, 10 в Приморске — 5,8 млн ₽.",
    "status": "draft",
    "morphologyApproved": true,
    "release": "starter-v2.1.0",
    "contentGateRule": "secondary"
  }
] as const satisfies readonly SeoRegistryRow<ProjectSeoTemplateKey>[];

assertSeoRegistry({ rows: projectSeoRegistrySeed, buildUrl: grammar.buildUrl, now: new Date("2026-09-24T12:00:00.000Z") });
