import assert from "node:assert/strict";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { PageKey } from "../src/core/routing/url-grammar.ts";
import {
	assertSeoRegistry,
	type SeoRegistryRow,
} from "../src/core/seo/registry.ts";
import { fixtureDistrictRouteRegistryFor } from "../src/fixture/route-registries.ts";
import { siteProfileFixtures } from "../src/project/site-profile.ts";
import {
	projectSeoTemplateKeys,
	type ProjectSeoTemplateKey,
} from "../src/project/seo/templates.ts";
import { createProjectUrlGrammar } from "../src/project/url-grammar.ts";

const sourcePath = resolve("docs/seo/SEO_REGISTRY_SEED.csv");
const generatedPath = resolve("src/project/seo/registry-seed.ts");
const columns = [
	"pageKey", "url", "canonical", "entityRef", "targetPhrases", "metric",
	"value", "source", "snapshotDate", "synthetic", "tier", "minimumObjects",
	"defaultRobots", "templateKey", "title", "h1", "description", "status",
	"morphologyApproved", "release", "contentGateRule",
] as const;

type CsvRow = Record<(typeof columns)[number], string>;
type GeneratedRow = SeoRegistryRow<ProjectSeoTemplateKey>;

const contentGateRules = new Set([
	"listing", "developerGeo", "development", "developer", "secondary", "newbuildLot",
]);

export function parseCsv(input: string): string[][] {
	const rows: string[][] = [];
	let row: string[] = [];
	let field = "";
	let quoted = false;
	for (let index = 0; index < input.length; index += 1) {
		const char = input[index];
		if (quoted) {
			if (char === '"' && input[index + 1] === '"') { field += '"'; index += 1; }
			else if (char === '"') quoted = false;
			else field += char;
		} else if (char === '"') quoted = true;
		else if (char === ",") { row.push(field); field = ""; }
		else if (char === "\n") { row.push(field.replace(/\r$/, "")); rows.push(row); row = []; field = ""; }
		else field += char;
	}
	if (quoted) throw new Error("CSV has an unterminated quoted field.");
	if (field || row.length) { row.push(field); rows.push(row); }
	return rows.filter((item) => item.some((value) => value.length > 0));
}

function boolean(value: string, field: string): boolean {
	if (value === "true") return true;
	if (value === "false") return false;
	throw new Error(`${field} must be true or false.`);
}

export function parseRegistryCsv(input: string): GeneratedRow[] {
	const [header, ...body] = parseCsv(input);
	assert.deepEqual(header, columns, "SEO CSV columns or order differ from contract");
	return body.map((values, index) => {
		if (values.length !== columns.length) throw new Error(`CSV row ${index + 2} has ${values.length} columns.`);
		const raw = Object.fromEntries(columns.map((column, offset) => [column, values[offset]])) as CsvRow;
		const pageKey = JSON.parse(raw.pageKey) as PageKey;
		const templateKey = raw.templateKey as ProjectSeoTemplateKey;
		if (!(projectSeoTemplateKeys as readonly string[]).includes(templateKey)) throw new Error(`Unknown templateKey: ${raw.templateKey}`);
		if (!raw.release || !raw.contentGateRule) throw new Error(`CSV row ${index + 2} requires release and contentGateRule.`);
		if (raw.release !== raw.release.trim()) throw new Error(`CSV row ${index + 2} release must not contain surrounding whitespace.`);
		if (raw.metric !== "searchDemand") throw new Error(`Unsupported metric: ${raw.metric}.`);
		if (!contentGateRules.has(raw.contentGateRule)) throw new Error(`Unsupported contentGateRule: ${raw.contentGateRule}.`);
		return {
			pageKey, url: raw.url, canonical: raw.canonical,
			entityRef: raw.entityRef || null,
			targetPhrases: raw.targetPhrases.split("|").map((value) => value.trim()).filter(Boolean),
			metric: raw.metric as "searchDemand",
			value: raw.value === "" ? null : Number(raw.value),
			source: raw.source as GeneratedRow["source"], snapshotDate: raw.snapshotDate,
			synthetic: boolean(raw.synthetic, "synthetic"), tier: raw.tier as GeneratedRow["tier"],
			minimumObjects: Number(raw.minimumObjects), defaultRobots: raw.defaultRobots as GeneratedRow["defaultRobots"],
			templateKey, title: raw.title, h1: raw.h1, description: raw.description,
			status: raw.status as GeneratedRow["status"], morphologyApproved: boolean(raw.morphologyApproved, "morphologyApproved"),
			release: raw.release, contentGateRule: raw.contentGateRule,
		};
	});
}

function generate(rows: readonly GeneratedRow[]): string {
	return `// Generated by pnpm seo:registry:generate. Do not edit manually.\nimport { assertSeoRegistry, type SeoRegistryRow } from "../../core/seo/registry.ts";\nimport { fixtureDistrictRouteRegistryFor } from "../../fixture/route-registries.ts";\nimport { siteProfileFixtures } from "../site-profile.ts";\nimport { createProjectUrlGrammar } from "../url-grammar.ts";\nimport type { ProjectSeoTemplateKey } from "./templates.ts";\n\nconst grammar = createProjectUrlGrammar(siteProfileFixtures.multiGeo, fixtureDistrictRouteRegistryFor(siteProfileFixtures.multiGeo));\n\nexport const projectSeoRegistrySeed = ${JSON.stringify(rows, null, 2)} as const satisfies readonly SeoRegistryRow<ProjectSeoTemplateKey>[];\n\nassertSeoRegistry({ rows: projectSeoRegistrySeed, buildUrl: grammar.buildUrl, now: new Date("2026-09-24T12:00:00.000Z") });\n`;
}

export function validateRegistryCsv(input: string): GeneratedRow[] {
	const rows = parseRegistryCsv(input);
	const grammar = createProjectUrlGrammar(siteProfileFixtures.multiGeo, fixtureDistrictRouteRegistryFor(siteProfileFixtures.multiGeo));
	assertSeoRegistry({ rows, buildUrl: grammar.buildUrl, now: new Date("2026-09-24T12:00:00.000Z") });
	return rows;
}

if (process.argv[1]?.endsWith("seo-registry.ts")) {
	const rows = validateRegistryCsv(readFileSync(sourcePath, "utf8"));
	const output = generate(rows);
	if (process.argv.includes("--check")) {
		assert.equal(readFileSync(generatedPath, "utf8").replaceAll("\r\n", "\n"), output, "Generated SEO registry is stale. Run pnpm seo:registry:generate.");
		console.log(`seo:registry:check PASS (${rows.length} rows)`);
	} else {
		writeFileSync(generatedPath, output, "utf8");
		console.log(`seo:registry:generate wrote ${rows.length} rows`);
	}
}
